CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"


#Touch 设置
TOUCH_TOKEN_INDEX = 32000 
DEFAULT_Touch_TOKEN = "<touch>"
DEFAULT_Touch_PATCH_TOKEN = "<th_patch>"
DEFAULT_Touch_START_TOKEN = "<th_start>"
DEFAULT_Touch_END_TOKEN = "<th_end>"
Touch_PLACEHOLDER = "<touch-placeholder>"
